export const JOIN_TEAM_ROOM = 'JOIN_TEAM_ROOM';
export const LEAVE_TEAM_ROOM = 'LEAVE_TEAM_ROOM';
export const BROADCAST_GAME_START = 'BROADCAST_GAME_START';
export const BROADCAST_JOINED_GAME = 'BROADCAST_JOINED_GAME';
export const ENTER_GEOFENCE = 'ENTER_GEOFENCE';
export const EXIT_GEOFENCE = 'EXIT_GEOFENCE';
export const BROADCAST_TASK_COMPLETE = 'BROADCAST_TASK_COMPLETE';
export const BROADCAST_END_GAME = 'BROADCAST_END_GAME';
