export const GAME_START = 'GAME_START';
export const JOINED_GAME = 'JOINED_GAME';
export const CONFIRM_TEAM_PRESENCE = 'CONFIRM_TEAM_PRESENCE';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const END_GAME = 'END_GAME';
